In [10]:
import numpy as np
from numpy import*

In [11]:
arr= array([2,3,8,9,7])#here array will act like function

In [12]:
print(arr)

[2 3 8 9 7]


In [13]:
print(arr.dtype)#checking data type , dtype means data type

int32


In [14]:
arr= array([2,3,8,9,7,7.5])#will be float data type
print(arr)
print(arr.dtype)

[2.  3.  8.  9.  7.  7.5]
float64


In [15]:
arr=array([2,3,4,5,6],int)
print(arr)

[2 3 4 5 6]


In [16]:
print(arr.dtype)

int32


In [17]:
#arr=linspace(start,end,parts)#three arguments, first two is mendatory

arr=linspace(0,15)#randomly create 50 values
print(arr)


[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]


In [26]:
arr=linspace(0,15,16)#randomly create 16 values
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


# Numpy using arange

In [19]:
#arr=arange(start,end,step) step is optional
arr=np.arange(1,15)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [20]:
arr=np.arange(1,15,2)
print(arr)

[ 1  3  5  7  9 11 13]


# Numpy array using logspace

In [29]:
#arr=logspace(start,end,part)

arr=logspace(1,40,5)

In [30]:
print(arr)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [31]:
print(arr[0])

10.0


In [32]:
print('%.2f'%arr[0]) #here %arr[0] will act like a variable

10.00


# Numpy array using Zeros

In [33]:
arr=zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [34]:
arr=zeros(5,int)
print(arr)

[0 0 0 0 0]


In [35]:
arr=zeros((4,3))#zeros(rows,columns) #by default float type
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [36]:
arr=zeros((4,3),int)#zeros(rows,columns) #by default float type
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


# 3D

In [38]:
arr=zeros((4,3,2),int)#3d array
print(arr)

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


# create numpy array from list

In [39]:
list=[1,2,3,4,5,6]
arr=np.array(list)

In [41]:
arr #for printing

array([1, 2, 3, 4, 5, 6])

In [43]:
list=[[1,2,3,4],[5,6,7,8]]
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
print(arr) #if we use print function then the word array will not be showed

[[1 2 3 4]
 [5 6 7 8]]


In [48]:
list=[[1,2,3,4],[5,6,7]]
arr=np.array(list)#it will not convert to two dimensional array because there should have same number of element in both arrays
arr

array([list([1, 2, 3, 4]), list([5, 6, 7])], dtype=object)

In [49]:
matrix=np.full(5,10)#full(number_of_elements,element)
matrix

array([10, 10, 10, 10, 10])

In [50]:
matrix=np.full((4,3),10)#for 2d
matrix

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [51]:
matrix=np.eye(3)# identity matrix
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
matrix=np.diag([4,5,6])# diagonal matrix
matrix

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

# Random Generation in Numpy

In [55]:
arr=np.random.rand(5)
arr

array([0.13180176, 0.57440364, 0.95001718, 0.55335135, 0.9782727 ])

In [57]:
arr=np.random.rand(3,5)#randomly 2d array
arr

array([[0.41280465, 0.48131475, 0.76399984, 0.05918801, 0.5106111 ],
       [0.86659533, 0.15924968, 0.85593028, 0.25916404, 0.47697694],
       [0.45579959, 0.67701784, 0.39309988, 0.70697303, 0.65849779]])

In [58]:
arr=np.random.rand(3,5,3)
arr

array([[[0.62701002, 0.99682463, 0.16261931],
        [0.16151228, 0.11663656, 0.425229  ],
        [0.72035574, 0.84003782, 0.39562408],
        [0.78200966, 0.27946615, 0.95753476],
        [0.61650385, 0.14925917, 0.80257137]],

       [[0.80867623, 0.14087264, 0.80503395],
        [0.03633151, 0.36445606, 0.71084971],
        [0.68825655, 0.63695544, 0.47786657],
        [0.24564811, 0.64196463, 0.47922374],
        [0.10212645, 0.86181524, 0.77546022]],

       [[0.0327059 , 0.92804295, 0.09598045],
        [0.15230949, 0.70993486, 0.02665815],
        [0.12913967, 0.20664353, 0.7681968 ],
        [0.00223364, 0.31637869, 0.1510288 ],
        [0.43930231, 0.85123936, 0.19203944]]])

In [59]:
arr=np.random.randn(5)#value will include positive and negative values
arr

array([ 0.94447586, -0.32396713,  2.03453968, -0.62136282, -0.09135365])

In [61]:
arr=np.random.randint(0,10,10)#range 0 to 9{10 not included}, and there will be 10values
arr

array([3, 1, 2, 4, 4, 8, 0, 4, 3, 9])

In [62]:
arr=np.random.randint(1,15,(4,4))#range 0 to 15{10 not included}, 4 rows 4 columns
arr

array([[ 4,  1,  2, 13],
       [ 2, 10,  4,  1],
       [ 2, 11, 14,  7],
       [ 9,  2, 10,  8]])

# Some functions in numpy

In [63]:
arr1=linspace(0,15,16)
print(arr1)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [66]:
arr2=ones((4,3),int)
print(arr2)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [68]:
arr1.ndim#checking dimension


1

In [70]:
arr2.ndim #checking dimension

2

In [71]:
arr1.shape#for checking row and column

(16,)

In [72]:
arr2.shape

(4, 3)

In [73]:
arr1.size#number of elements

16

In [74]:
arr2.size

12

In [75]:
arr1.dtype#checking datatype

dtype('float64')

In [76]:
arr1.data#locations of array data

# Indexing in Numpy

In [77]:
arr=linspace(0,15,16)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [78]:
for data in arr:
    print(data,end=" ")

0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0 12.0 13.0 14.0 15.0 

In [79]:
for i in range(len(arr)):
    print(arr[i],end=" ")

0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0 12.0 13.0 14.0 15.0 

In [81]:
print(arr[1:5])#5 not included

[1. 2. 3. 4.]


In [82]:
print(arr[:6])#by default from index 0

[0. 1. 2. 3. 4. 5.]


In [83]:
arr1=arr[5:]
arr1

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.])

In [84]:
arr2=arr1.copy
arr2

<function ndarray.copy>

In [85]:
print(arr2)

<built-in method copy of numpy.ndarray object at 0x000002139AB1B580>


# Reshape and ravel function in Numpy

In [91]:
arr =np.random.randint(1,20,(5,5))
arr

array([[ 1,  3, 11,  4, 14],
       [ 5,  4, 19, 18,  8],
       [ 6,  9,  3, 11,  4],
       [ 2, 12, 17,  7,  8],
       [ 9,  3, 17, 16,  6]])

In [94]:
a1=arr[0:4,0:3]
a1

array([[ 1,  3, 11],
       [ 5,  4, 19],
       [ 6,  9,  3],
       [ 2, 12, 17]])

In [95]:
a1.shape

(4, 3)

In [97]:
arr1=a1.reshape(3,4)
arr1

array([[ 1,  3, 11,  5],
       [ 4, 19,  6,  9],
       [ 3,  2, 12, 17]])

In [99]:
#arr2=a1.reshape(6,3)#error because total number of elemenets is not the same
#arr2

In [101]:
arr2=a1.reshape(6,2)
arr2

array([[ 1,  3],
       [11,  5],
       [ 4, 19],
       [ 6,  9],
       [ 3,  2],
       [12, 17]])

In [103]:
#2d to 1d array
arr3=arr1.ravel()
arr3

array([ 1,  3, 11,  5,  4, 19,  6,  9,  3,  2, 12, 17])

# Arithmetic Operation in Numpy and Reshape function

In [107]:
arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [109]:
print(arr+arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [110]:
print(arr-arr)

[0 0 0 0 0 0 0 0 0 0 0 0]


In [111]:
print(arr*arr)

[  1   4   9  16  25  36  49  64  81 100 121 144]


In [112]:
print(arr/arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [113]:
arr=np.arange(0,13)# in case of division there will be an error because one of the elements is zero
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [115]:
arr1=a1.reshape(3,4)
arr1

array([[ 1,  3, 11,  5],
       [ 4, 19,  6,  9],
       [ 3,  2, 12, 17]])

In [116]:
arr2=a1.reshape(6,2)
arr2

array([[ 1,  3],
       [11,  5],
       [ 4, 19],
       [ 6,  9],
       [ 3,  2],
       [12, 17]])

In [120]:
#print(arr1+arr2) #will be an error because the shape of the arrays are not same 
print(arr1+arr2.reshape(3,4))
arr3=arr1+arr2.reshape(3,4)

[[ 2  6 22 10]
 [ 8 38 12 18]
 [ 6  4 24 34]]


In [122]:
arr3.sum(axis=0)#sum of every columns

array([16, 48, 58, 62])

In [123]:
arr3.sum(axis=1)#sum of every rows

array([40, 76, 68])

# Array selection in Numpy

In [126]:
arr=np.random.randint(1,15,(6,5))
arr

array([[ 3,  9,  9, 12,  6],
       [ 7,  2,  6, 11,  5],
       [ 1,  5,  1,  3, 11],
       [ 6,  2,  1,  9, 12],
       [14,  3,  2,  5,  4],
       [ 1, 11,  4,  8,  1]])

In [127]:
a1=arr[0:4,0:3]
a1

array([[3, 9, 9],
       [7, 2, 6],
       [1, 5, 1],
       [6, 2, 1]])

In [129]:
a2=arr[4:,]#includes all columns
a2

array([[14,  3,  2,  5,  4],
       [ 1, 11,  4,  8,  1]])

In [130]:
a3=arr[3:5,2:4]
a3

array([[1, 9],
       [2, 5]])

In [134]:
bool_m = a1>6 #all the elemnts greater than 6 will store True value
bool_m

array([[False,  True,  True],
       [ True, False, False],
       [False, False, False],
       [False, False, False]])